#!/bin/sh
# source /home/tomek/.rvm/scripts/rvm

#http://stackoverflow.com/questions/18290080/change-rails-version-used-by-rvm
#rvm gemset empty
#rvm use @rails3
#gem install rails -v "~>3.2"
#rvm use @rails4
#gem install rails -v "~>4"
#rvm use 2.0.0@rails3
#rails -v             # rails 3.2...
#rvm use 2.0.0@rails4
#rails -v             # rails 4.0...

rvm use 2.1.3@rails4
mkdir $1
cd $1
git init
git remote add $1 https://github.com/miodzio4/roses.git <../generators/git-crdnt
git pull --force $1 master <../generators/git-crdnt
git rm -r -f .
git commit -m "Adding $1 baseline" 
git push --force $1 master
cd ..

rails new $1
cp generators/rails4-sqlite-postgress/reference/Gemfile $1
#cp generators/rails4-sqlite-postgress/reference/database.yml $1/config/

cd $1
bundle update 
bundle install
rails generate formtastic:install 
#rails g nifty:layout
#cp ../generators/rails3-postgress-postgress/reference/application.html.erb  app/views/layouts/

rails generate scaffold Rose name:string description:string flower_color_id:integer flower_color_desc:string synonims:string milddew_imm_id:integer leaves_color:string leaf_spot_imm_id:integer fragrance_id:integer height_id:integer height_text:string freeze_imm_id:integer type_id:integer year:string origin:string ADR:boolean flower_shape:string cultivation:string remarks:string
rails generate scaffold flower_color name:string description:string
rails generate scaffold milddew_imm name:string description:string
rails generate scaffold leaf_spot_imm name:string description:string
rails generate scaffold fragrance name:string description:string
rails generate scaffold height name:string description:string
rails generate scaffold freeze_imm name:string description:string
rails generate scaffold type name:string description:string

rails generate scaffold Search name:string flower_color_id:integer milddew_imm_id:integer leaf_spot_imm_id:integer fragrance_id:integer height_id:integer freeze_imm_id:integer type_id:integer ADR:boolean


rails generate scaffold flower_color_search search_id:integer flower_color_id:integer --skip-controller
rails generate scaffold milddew_imm_search search_id:integer milddew_imm_id:integer --skip-controller
rails generate scaffold leaf_spot_imm_search search_id:integer leaf_spot_imm_id:integer --skip-controller
rails generate scaffold freeze_imm_search search_id:integer freeze_imm_id:integer --skip-controller
rails generate scaffold type_search search_id:integer type_id:integer --skip-controller
rails generate scaffold fragrance_search search_id:integer fragrance_id:integer --skip-controller
rails generate scaffold height_search search_id:integer height_id:integer --skip-controller

rake db:create:all
bundle exec rake db:migrate
cp -r ../generators/rails4-sqlite-postgress/reference/app .


git add .
git commit -m "$1 first commit"
#git remote add origin https://github.com/miodzio4/roses.git <../generators/git-crdnt
git push -u -f $1 master


#bundle install --without production
#rake assets:precompile
rake assets:precompile RAILS_ENV=production
git commit -a -m "Add precompiled assets for Heroku"

heroku login <../generators/her-crdnt
sudo heroku git:remote -a gentle-river-6914 
sudo git push -f heroku master
heroku pg:reset DATABASE_URL --confirm gentle-river-6914
heroku run rake db:migrate
heroku open



